### PR TITLE
:trollface:

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kacorvixon1337** [comment]
dobre

**Review by WcaleNieWolny — COMMENTED** [review]
Why is this called roseHC? What even is roseHC? Why have you implemented so much unrelated features such as coblex, discord reward (?), disco effects and a lot more features unrelated to this project? Giving a proper review of this will take a lot of time, but please note that this is not the final PR review.

**Review by ivall — APPROVED** [review]
lgtm

**Comment by dzikoysk** [comment]
Kod prezentuje za wysoki standard jak na naszą organizację, zamykam

**Pull request closed without merging**
